spring:
  profiles:
    active: production
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  oauth2:
    resource:
      tokenInfoUri: ${TOKEN_INFO_URI}

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /
      exposure:
        include: health, metrics
  server:
    port: ${MANAGEMENT_PORT:7979}

twintip:
  mapping: /api
  yaml: "classpath:/api/zally-api.yaml"

rules-config-path: "rules-config.conf"

zally:
  ignoreRules: M008, M009, M010, M011, H001, H002, S005, S006, S007
  rules:
    - org.zalando.zally.ruleset.roedl.RoedlRuleSet
    - org.zalando.zally.ruleset.zally.ZallyRuleSet
  cli:
    releasesPage: https://github.com/zalando/zally/releases
    deprecatedCliAgents: unirest-java/1.3.11,Zally-CLI/1.0
---
spring.profiles: local
TOKEN_INFO_URI: https://auth.example.com/oauth2/tokeninfo
